### ISSUE TITLE
Web UI yt-dlp upgrader is not working

### ISSUE THREAD

**Issue by Gladzy86** [vicwomg/pikaraoke#238]
Hi,

Firstly, this looks great and can't wait to get it up and running!

I have flashed your image to my pi 3 and followed the instructions to connect to WiFi, but whenever I try to run pikaraoke I get the following message at the bottom of the screen:

WiFi/Network not connected

I have tried to use an ethernet connection and managed to connect but the when I try to download from YouTube, the songs never appear in my list. I have followed the instructions re updating youtube-dl and expanding the SD card.

Whenever I have tried to download from YouTube, I get the message to inform me it's downloading but never does, I've waited for about an hour to download one song so I assume it's not working!

Ideally I would like to be able to connect to WiFi and tackle that problem first! Any suggestions would be much appreciated, thanks in advance.

Mark

**Comment by vicwomg** [comment]
what are the contents of your wpa_supplicant file? My guess is that it isn't correctly formatted.

**Comment by vicwomg** [comment]
See this guide. Sometimes certain text editors will screw up the line breaks when editing files:

https://www.raspberrypi-spy.co.uk/2017/04/manually-setting-up-pi-wifi-using-wpa_supplicant-conf/

**Comment by Gladzy86** [comment]
Thank you, I can see where I was going wrong... trying to connect to 5G when my Pi doesn't support it!

I am still having problems downloading songs though, I have tried to update youtube-dl, I'm currently on version 2022.04.08. I can search with no problems and get a notification to say my song is downloading but it never appears in the browser, any ideas where I'm going wrong here?

Thanks

**Comment by Gladzy86** [comment]
I have upgraded yt-dlp with:

pip3 install --upgrade yt-dlp

to the latest version but the pikaraoke is still showing 2022.04.08 version and still no downloads!

**Comment by vicwomg** [comment]
your yt-dlp is out of date and that is likely why the downloads  are failing. My guess is you have two versions of yt-dlp, the one pikaraoke is using is not being upgraded. You shouldn't need to do it with pip3, there's a feature in the web UI to do it:  `Info > Update Youtube-dl`. Did you try that?

If you do try the command line, you need to run this to upgrade: `sudo /usr/local/bin/yt-dlp -U` assuming everything is installed in the default place.

**Comment by vicwomg** [comment]
Actually, I think I see a bug in the upgrader!

This line:
https://github.com/vicwomg/pikaraoke/blob/8da02e191026e506a0f624042f5a95f8840d1153/karaoke.py#L239

Will always fail because it should say `It looks like you installed yt-dlp with a package manager ` (not youtube-dl, which was deprecated)

That prevents the upgrade from happening the correct way.

If you want to manually update, you can run this from the CLI:
`sudo pip3 install --upgrade yt-dlp` 

I noticed you were missing the sudo. That might have been the issue.

**Comment by vicwomg** [comment]
upgrade should be fixed now. Run `git pull` from your pikaraoke directory to get the latest code, restart, and upgrading via the web interface should work now. Let me know if that does the trick

**Comment by Gladzy86** [comment]
Ah so sorry, I'm in the process of moving at the moment... as soon as I have unpacked the pi I'll test it out and let you know. Thank you!

**Comment by kylehild** [comment]
I did a git pull and then tried updating through the UI. I still got the same issue described by @vicwomg in my log file.

**Comment by tabzz73** [comment]
> upgrade should be fixed now. Run `git pull` from your pikaraoke directory to get the latest code, restart, and upgrading via the web interface should work now. Let me know if that does the trick

Still not working for me still shows the old version. Manual update did work though

**Comment by vicwomg** [comment]
I have merged another fix and verified it on my own pi 4. Let me know if it works for you and I will update the master image if so.

**Comment by vicwomg** [comment]
> > I have merged another fix and verified it on my own pi 4. Let me know if it works for you after another `git pull` and I will update the master pi image if so.
> 
> Thanks for everything! "git pull" still did not work for me, but the manual update did.

There seems to be a misunderstanding. `git pull` alone doesn't upgrade yt-dlp. That just fetches the latest pikaraoke version, however the latest version should fix yt-dlp upgrades not working from the pikaraoke menu. I'd really like someone to confirm that this works for them.

**Comment by ShortyVee** [comment]
@vicwomg the latest changes worked for me on Raspberry Pi 3

**Comment by vicwomg** [comment]
Most excellent, thanks for confirming @ShortyVee

**Comment by bingobob** [comment]
two things.

1) this project looks amazing - thanks so much - love the clean interface, minimalism, love it. Big weekend this one for the UK - what better time for a karaoke party - pleaase keep dev-ing this - is lovely!

2) can confirm with your brilliant updte that the info here fixed the yt-dlp upgrade issue for me also.

i.e.

ALL IS GOOD !

thanks again.
